version: 2.1
jobs:
  install-lint:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build-upload-image:
    docker:
      - image: circleci/node:14 # Use a CircleCI Docker image as the build environment
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Use the appropriate Docker version

      # Build the Docker image
      - run:
          name: Build Docker Image
          command: docker build -t harishbabua/capstone:latest .

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push harishbabua/capstone:latest

workflows:
  default:
    jobs:
      - install-lint
      - build-upload-image:
          requires: [install-lint]
